author: MoceanAPI
category: marketing
compatible_versions: 1.0.0+
description: description.md
description_short: "Make your thirty bees store more user friendly by giving your store the capabilities of notifying your customers about order status."
gdpr_compliant: true
license: OSL
images:
  - image-1.png
  - image-2.png
  - image-3.png
  - image-4.png
  - image-5.png
  - image-6.png
  - image-7.png
localization:
- EN
- CS
module_name: "MoceanAPI module"
php_version:
- 5.3
- 5.4
- 5.5
- 5.6
tags:
- sms
- send sms
- sms notifications
- bulk sms
- thirty bees
- thirty bees sms
- sms thirty bees
- sms order
- sms order notification
- customer notification
- notify admin
- sms campaign
- sms plugin
- sms module
- eshop
- ecommerce
- sms marketing
- target marketing
- sms api
- sms gateway
- sms alerts
- alerts
- notifications
- order status
- marketing campaigns
- custom hooks
- thirty bees sms notifications
- affiliate program
- order sms notifications
- order notifications via sms
- sms notification module
- moceanapi
